sudo docker run -d -p 3000:3000 -v ./config:/app/config -v /var/run/docker.sock:/var/run/docker.sock \
  -e HOMEPAGE_VAR_PROXMOX_USERNAME=$HOMEPAGE_VAR_PROXMOX_USERNAME \
  -e HOMEPAGE_VAR_PROXMOX_PASSWORD=$HOMEPAGE_VAR_PROXMOX_PASSWORD \
  -e HOMEPAGE_VAR_TRUENAS_USERNAME=$HOMEPAGE_VAR_TRUENAS_USERNAME \
  -e HOMEPAGE_VAR_TRUENAS_PASSWORD=$HOMEPAGE_VAR_TRUENAS_PASSWORD \
  -e HOMEPAGE_VAR_PF_USERNAME=$HOMEPAGE_VAR_PF_USERNAME \
  -e HOMEPAGE_VAR_PF_PASSWORD=$HOMEPAGE_VAR_PF_PASSWORD \
  -e HOMEPAGE_VAR_KUMA=$HOMEPAGE_VAR_KUMA \
  -e HOMEPAGE_VAR_HA_KEY=$HOMEPAGE_VAR_HA_KEY \
  -e HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID=$HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID \
  -e HOMEPAGE_VAR_CLOUDFLARE_KEY=$HOMEPAGE_VAR_CLOUDFLARE_KEY \
  -e HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_PVE=$HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_PVE \
  -e HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_KUMA=$HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_KUMA \
  -e HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_GUACAMOLE=$HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_GUACAMOLE \
  -e HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_RESUME=$HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_RESUME \
  -e HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_DENY=$HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_DENY \
  ghcr.io/gethomepage/homepage:latest
